// Generated by website-builder from design-repo/tokens/ (source: https://moment.com/). Tailwind v3. Do not hand-edit; re-run the scrape.
// Values are measured from computed styles; names are heuristic. Nothing here overrides Tailwind's default scales.
// Breakpoints: bp-<px> = min-width, bp-max-<px> = max-width (measured from the site's CSS media queries).
export default {
  corePlugins: { preflight: false }, // the site's own CSS is the reset
  "content": [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx,html}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "neutral-01": "rgb(250,251,251)",
        "neutral-02": "rgb(255,255,255)",
        "teal-01": "rgb(90,123,125)",
        "teal-02": "rgb(47,64,65)",
        "neutral-03": "rgb(247,248,248)",
        "teal-03": "rgb(169,188,188)",
        "teal-04": "rgb(221,231,231)",
        "neutral-04": "rgb(0,0,0)",
        "teal-05": "rgb(70,99,99)",
        "neutral-05": "rgb(51,51,51)",
        "neutral-06": "rgba(17,29,27,0.9)",
        "neutral-07": "rgb(238,243,243)",
        "teal-06": "rgb(181,213,215)",
        "teal-07": "rgb(24,51,53)",
        "teal-08": "rgb(33,61,62)",
        "neutral-08": "rgb(17,29,27)",
        "neutral-09": "rgba(17,29,27,0.85)",
        "teal-09": "rgba(169,188,188,0.07)",
        "neutral-10": "rgba(17,29,27,0.55)",
        "neutral-11": "rgba(168,175,172,0.8)",
        "teal-10": "rgba(24,51,53,0.6)",
        "surface-default": "rgba(17,29,27,0.9)",
        "surface-alt": "rgb(238,243,243)",
        "surface-inverse": "rgb(238,243,243)",
        "surface-accent": "rgb(24,51,53)",
        "text-primary": "rgb(250,251,251)",
        "text-secondary": "rgb(169,188,188)",
        "text-inverse": "rgb(70,99,99)",
        "text-accent": "rgb(24,51,53)",
        "border-default": "rgb(51,51,51)",
        "accent-primary": "rgb(24,51,53)"
      },
      "spacing": {
        "sp-1": "1px",
        "sp-2": "2px",
        "sp-2_5": "2.5px",
        "sp-4": "4px",
        "sp-5": "5px",
        "sp-5_5": "5.5px",
        "sp-6": "6px",
        "sp-6_5": "6.5px",
        "sp-8": "8px",
        "sp-11": "11px",
        "sp-12": "12px",
        "sp-16": "16px",
        "sp-20": "20px",
        "sp-24": "24px",
        "sp-28": "28px",
        "sp-32": "32px",
        "sp-40": "40px",
        "sp-50": "50px",
        "sp-80": "80px",
        "sp-96": "96px",
        "sp-108": "108px",
        "sp-140": "140px",
        "sp-144": "144px",
        "sp-190": "190px",
        "gutter": "444px"
      },
      "borderRadius": {
        "r-4": "4px",
        "r-1": "1px",
        "r-3": "3px",
        "r-2": "2px",
        "control": "4px",
        "surface": "1px"
      },
      "fontFamily": {
        "ff-01": [
          "\"twkLausanne\"",
          "sans-serif"
        ],
        "ff-02": [
          "\"STIX Two Text\"",
          "sans-serif"
        ],
        "ff-03": [
          "\"twkEverettMono\"",
          "sans-serif"
        ],
        "ff-04": [
          "\"JetBrains Mono\"",
          "sans-serif"
        ],
        "display": [
          "\"twkLausanne\"",
          "sans-serif"
        ],
        "heading": [
          "\"twkLausanne\"",
          "sans-serif"
        ],
        "body": [
          "\"twkLausanne\"",
          "sans-serif"
        ],
        "label": [
          "\"twkLausanne\"",
          "sans-serif"
        ]
      },
      "fontSize": {
        "fs-10": "10px",
        "fs-12": "12px",
        "fs-13": "13px",
        "fs-14": "14px",
        "fs-16": "16px",
        "fs-18": "18px",
        "fs-20": "20px",
        "fs-24": "24px",
        "fs-28": "28px",
        "fs-32": "32px",
        "fs-35": "35px",
        "fs-40": "40px",
        "display": [
          "40px",
          {
            "lineHeight": "48px",
            "fontWeight": "350"
          }
        ],
        "heading": [
          "10px",
          {
            "lineHeight": "15px",
            "fontWeight": "400"
          }
        ],
        "body": [
          "16px",
          {
            "lineHeight": "26px",
            "fontWeight": "350"
          }
        ],
        "label": [
          "14px",
          {
            "lineHeight": "20px",
            "fontWeight": "350"
          }
        ]
      },
      "transitionDuration": {
        "d-200ms": "0.2s",
        "d-300ms": "0.3s",
        "d-650ms": "0.65s",
        "d-150ms": "0.15s",
        "d-350ms": "0.35s",
        "d-400ms": "0.4s",
        "d-NaNms": "auto",
        "d-1680ms": "1.68s",
        "motion-default": "0.2s"
      },
      "transitionTimingFunction": {
        "ease-01": "ease",
        "ease-02": "cubic-bezier(0.4, 0, 0.2, 1)",
        "ease-03": "linear",
        "ease-04": "cubic-bezier(0.16, 1, 0.3, 1)",
        "ease-05": "cubic-bezier(0.25, 0.1, 0.25, 1)",
        "ease-06": "cubic-bezier(0.4, 0, 1, 1)",
        "motion-default": "ease"
      },
      "screens": {
        "bp-400": {
          "min": "400px"
        },
        "bp-500": {
          "min": "500px"
        },
        "bp-599": {
          "min": "599px"
        },
        "bp-600": {
          "min": "600px"
        },
        "bp-800": {
          "min": "800px"
        },
        "bp-928": {
          "min": "928px"
        },
        "bp-1000": {
          "min": "1000px"
        },
        "bp-1200": {
          "min": "1200px"
        },
        "bp-max-640": {
          "max": "640px"
        },
        "bp-max-360": {
          "max": "360px"
        }
      },
      "maxWidth": {
        "content": "1440px"
      }
    }
  },
  "plugins": []
};
