// IA section(s): content.section (ia/ia.json, design-repo/sections/)
// section — the section's real markup, read from the rendered page (route /memo, section 2).
export default function Section() {
  return (
    <section className="relative" data-clone-section="Section">
      <div aria-hidden="true" className="pointer-events-none absolute top-0 left-0 h-706 w-250 min-[800px]:hidden" style={{ "maskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)", "WebkitMaskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)" }}>
        <div className="absolute inset-0 will-change-[background-position] motion-reduce:animate-none animate-memo-hero-sweep-ltr" style={{ "maskImage": "url(\"/graphics/about/hero-mobile-left.svg\")", "WebkitMaskImage": "url(\"/graphics/about/hero-mobile-left.svg\")", "maskRepeat": "no-repeat", "WebkitMaskRepeat": "no-repeat", "maskSize": "100% 100%", "WebkitMaskSize": "100% 100%", "backgroundColor": "var(--color-graphic-details)", "backgroundImage": "linear-gradient(to right, rgba(221, 231, 231, 0) 0%, rgba(221, 231, 231, 0) 35%, rgba(221, 231, 231, 0.42) 50%, rgba(221, 231, 231, 0) 65%, rgba(221, 231, 231, 0) 100%)", "backgroundSize": "220% 100%", "backgroundRepeat": "no-repeat" }}></div>
      </div>
      <div aria-hidden="true" className="pointer-events-none absolute top-0 right-0 h-706 w-257 min-[800px]:hidden" style={{ "maskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)", "WebkitMaskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)" }}>
        <div className="absolute inset-0 will-change-[background-position] motion-reduce:animate-none animate-memo-hero-sweep-rtl" style={{ "maskImage": "url(\"/graphics/about/hero-mobile-right.svg\")", "WebkitMaskImage": "url(\"/graphics/about/hero-mobile-right.svg\")", "maskRepeat": "no-repeat", "WebkitMaskRepeat": "no-repeat", "maskSize": "100% 100%", "WebkitMaskSize": "100% 100%", "backgroundColor": "var(--color-graphic-details)", "backgroundImage": "linear-gradient(to right, rgba(221, 231, 231, 0) 0%, rgba(221, 231, 231, 0) 35%, rgba(221, 231, 231, 0.42) 50%, rgba(221, 231, 231, 0) 65%, rgba(221, 231, 231, 0) 100%)", "backgroundSize": "220% 100%", "backgroundRepeat": "no-repeat" }}></div>
      </div>
      <div aria-hidden="true" className="pointer-events-none absolute top-0 left-0 hidden h-760 w-219 min-[800px]:block min-[1000px]:hidden" style={{ "maskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)", "WebkitMaskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)" }}>
        <div className="absolute inset-0 will-change-[background-position] motion-reduce:animate-none animate-memo-hero-sweep-ltr" style={{ "maskImage": "url(\"/graphics/about/hero-tablet-left.svg\")", "WebkitMaskImage": "url(\"/graphics/about/hero-tablet-left.svg\")", "maskRepeat": "no-repeat", "WebkitMaskRepeat": "no-repeat", "maskSize": "100% 100%", "WebkitMaskSize": "100% 100%", "backgroundColor": "var(--color-graphic-details)", "backgroundImage": "linear-gradient(to right, rgba(221, 231, 231, 0) 0%, rgba(221, 231, 231, 0) 35%, rgba(221, 231, 231, 0.42) 50%, rgba(221, 231, 231, 0) 65%, rgba(221, 231, 231, 0) 100%)", "backgroundSize": "220% 100%", "backgroundRepeat": "no-repeat" }}></div>
      </div>
      <div aria-hidden="true" className="pointer-events-none absolute top-0 right-0 hidden h-760 w-228 min-[800px]:block min-[1000px]:hidden" style={{ "maskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)", "WebkitMaskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)" }}>
        <div className="absolute inset-0 will-change-[background-position] motion-reduce:animate-none animate-memo-hero-sweep-rtl" style={{ "maskImage": "url(\"/graphics/about/hero-tablet-right.svg\")", "WebkitMaskImage": "url(\"/graphics/about/hero-tablet-right.svg\")", "maskRepeat": "no-repeat", "WebkitMaskRepeat": "no-repeat", "maskSize": "100% 100%", "WebkitMaskSize": "100% 100%", "backgroundColor": "var(--color-graphic-details)", "backgroundImage": "linear-gradient(to right, rgba(221, 231, 231, 0) 0%, rgba(221, 231, 231, 0) 35%, rgba(221, 231, 231, 0.42) 50%, rgba(221, 231, 231, 0) 65%, rgba(221, 231, 231, 0) 100%)", "backgroundSize": "220% 100%", "backgroundRepeat": "no-repeat" }}></div>
      </div>
      <div aria-hidden="true" className="pointer-events-none absolute top-0 left-0 hidden h-911 w-426 min-[1000px]:block" style={{ "maskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)", "WebkitMaskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)" }}>
        <div className="absolute inset-0 will-change-[background-position] motion-reduce:animate-none animate-memo-hero-sweep-ltr" style={{ "maskImage": "url(\"/graphics/about/hero-desktop-left.svg\")", "WebkitMaskImage": "url(\"/graphics/about/hero-desktop-left.svg\")", "maskRepeat": "no-repeat", "WebkitMaskRepeat": "no-repeat", "maskSize": "100% 100%", "WebkitMaskSize": "100% 100%", "backgroundColor": "var(--color-graphic-details)", "backgroundImage": "linear-gradient(to right, rgba(221, 231, 231, 0) 0%, rgba(221, 231, 231, 0) 35%, rgba(221, 231, 231, 0.42) 50%, rgba(221, 231, 231, 0) 65%, rgba(221, 231, 231, 0) 100%)", "backgroundSize": "220% 100%", "backgroundRepeat": "no-repeat" }}></div>
      </div>
      <div aria-hidden="true" className="pointer-events-none absolute top-0 right-0 hidden h-911 w-426 min-[1000px]:block" style={{ "maskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)", "WebkitMaskImage": "linear-gradient(to bottom, transparent 18%, black 33%, black 58%, transparent 73%)" }}>
        <div className="absolute inset-0 will-change-[background-position] motion-reduce:animate-none animate-memo-hero-sweep-rtl" style={{ "maskImage": "url(\"/graphics/about/hero-desktop-right.svg\")", "WebkitMaskImage": "url(\"/graphics/about/hero-desktop-right.svg\")", "maskRepeat": "no-repeat", "WebkitMaskRepeat": "no-repeat", "maskSize": "100% 100%", "WebkitMaskSize": "100% 100%", "backgroundColor": "var(--color-graphic-details)", "backgroundImage": "linear-gradient(to right, rgba(221, 231, 231, 0) 0%, rgba(221, 231, 231, 0) 35%, rgba(221, 231, 231, 0.42) 50%, rgba(221, 231, 231, 0) 65%, rgba(221, 231, 231, 0) 100%)", "backgroundSize": "220% 100%", "backgroundRepeat": "no-repeat" }}></div>
      </div>
      <div aria-hidden="true" className="pointer-events-none invisible h-706 min-[1000px]:h-911 min-[800px]:h-760"></div>
      <div className="absolute inset-0 flex flex-col items-center gap-y-80 px-16 pt-265 text-center text-text-primary min-[1200px]:gap-y-96">
        <p data-page-reveal="1" className="max-w-510 text-balance text-[2.4rem] uppercase leading-[2.8rem] min-[1000px]:max-w-556 min-[1000px]:leading-[3.2rem]">THE AI OPERATING SYSTEM FOR INVESTMENT MANAGEMENT</p>
        <p data-page-reveal="2" className="text-[2rem] leading-[2.8rem] min-[1000px]:leading-[3.2rem]">Dylan Parker</p>
        <p data-page-reveal="3" className="text-[2rem] leading-[2.8rem] min-[1000px]:leading-[3.2rem]">May 2026</p>
      </div>
    </section>
  );
}
